/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.hvf.alephnull.fact.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Operation implements org.apache.thrift.TEnum {
  NO_OP(0),
  SYNCH_TIME_OP(1),
  IDENTITY_OP(2),
  BLOBSTORE_OP(99);

  private final int value;

  private Operation(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Operation findByValue(int value) { 
    switch (value) {
      case 0:
        return NO_OP;
      case 1:
        return SYNCH_TIME_OP;
      case 2:
        return IDENTITY_OP;
      case 99:
        return BLOBSTORE_OP;
      default:
        return null;
    }
  }
}
